### ISSUE TITLE
Plugin Folder Structure

### ISSUE THREAD

**Issue by fpcorso** [gamekid88/final-quote-plugin#1]
So, there are a few ways to structure your plugin's directory. The most common way:
### Main Directory
- Main File
- readme.txt
- uninstall.php
- assets folder
- includes folder
- languages folder

Then, inside your includes folder, you would have your extra files such as you shortcode and admin files. Inside the includes folder, you could have folders for css, js, php, etc..

Another common way is to just have the different folders in the main directory like this:
### Main Directory
- Main File
- readme.txt
- uninstall.php
- assets folder
- css folder
- js folder
- php folder
- languages folder

**Comment by fpcorso** [comment]
### Main Directory
* Main File
* readme.txt
* uninstall.php
* assets folder
* includes folder
* languages folder

Then, inside your includes folder, you would have your extra files such as you shortcode and admin files. Inside the includes folder, you could have folders for css, js, php, etc..

Another common way is to just have the different folders in the main directory like this:

= Main Directory =
* Main File
* readme.txt
* uninstall.php
* assets folder
* css folder
* js folder
* php folder
* languages folder

**Comment by gamekid88** [comment]
Ok I committed the update to the file structure of the repo.
